routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', [\App\Http\Controllers\AdsController::class, 'index']);

Route::middleware('auth')->name('ads.')->prefix('ads')->group(function() {
    Route::get('/', [\App\Http\Controllers\AdsController::class, 'index'])->name('index');
    Route::get('/create', [\App\Http\Controllers\AdsController::class, 'create'])->name('create');
    Route::post('/', [\App\Http\Controllers\AdsController::class, 'store'])->name('store');
    Route::get('/{ad}/edit', [\App\Http\Controllers\AdsController::class, 'edit'])->can('update', 'ad')->name('edit');
    Route::put('/{ad}/', [\App\Http\Controllers\AdsController::class, 'update'])->can('update', 'ad')->name('update');
    Route::delete('/{ad}/', [\App\Http\Controllers\AdsController::class, 'destroy'])->can('delete', 'ad')->name('destroy');
});

Route::name('ads.')->prefix('ads')->group(function() {
    Route::get('/{id}', [\App\Http\Controllers\AdsController::class, 'show'])->name('show');
});

Route::post('login', [\App\Http\Controllers\AuthController::class, 'login'])->middleware('guest');
Route::get('logout', [\App\Http\Controllers\AuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::get('login', fn() => redirect('/'))->name('login');
Route::get('/callback', [\App\Http\Controllers\GitlabController::class, 'callback'])->middleware('guest');

app/Models/Ad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    
    protected $fillable = [
        'title',
        'description',
        'author_id',
    ];
    
    use HasFactory;
    
    public function author() {
        return $this->belongsTo(User::class, 'author_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function ads() {
        return $this->hasMany(Ad::class, 'author_id');
    }

}

app/Http/Controllers/AdsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Ad;

class AdsController extends Controller
{
    public function index() {
        $ads = Ad::with(['author'])->orderBy('created_at', 'desc')->paginate(5);

        return view('ads.index', compact('ads'));
    }

    public function create() {
        return view('ads.create');
    }

    public function store(Request $request) {

        $request->validate([
            'title' => ['required', 'min:3', 'max:255'],
            'description' => ['required'],
        ]);

        $data = $request->all();
        $data['author_id'] = Auth::id();
        Ad::create($data);

        return redirect()->route('ads.index');
    }

    public function show($id) {
        $ad = Ad::find($id);
        return view('ads.show', compact('ad'));
    }

    public function edit(Ad $ad) {
        return view('ads.update', compact('ad'));
    }

    public function update(Request $request, Ad $ad) {
        $request->validate([
            'title' => ['required', 'min:3', 'max:255'],
            'description' => ['required'],
        ]);

        $ad->update($request->all());
        return redirect()->route('ads.index');
    }

    public function destroy(Ad $ad) {
       $ad->delete();
       return redirect()->route('ads.index');
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use App\Models\Ad;
use App\Models\User;

class AuthController extends Controller
{
    public function login(Request $request) {

       $credentials = $request->validate([
           'email' => ['required'],
           'password' => ['required']
       ]);

       $user = User::query()->where('email', '=' ,$credentials['email'])->first();

       if(null === $user) {

           $credentials = $request->validate([
                'email' => ['required', 'unique:users,email'],
                'password' => ['required']
           ]);

           $user = User::create([
               'first_name' => '',
               'last_name' => '',
               'email' => $credentials['email'],
               'password' => Hash::make($credentials['password'])
           ]);
       } else {
           if(!Hash::check($credentials['password'], $user->password)) {
                    return back()->withErrors(['email' => 'The provided credentials do not match our records.']);
           }
       }

       Auth::login($user);

       $request->session()->regenerate();

       return back();
    }

    public function logout(Request $request) {

       Auth::logout();

       $request->session()->invalidate();
       $request->session()->regenerateToken();

       return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GitlabController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class GitlabController extends Controller
{
    public function callback(Request $request) {

       $response = Http::withHeaders(['Accept' => 'application/json'])
            ->asForm()
            ->post('https://gitlab.com/oauth/token', [
                'client_id' => config('oauth.gitlab.client_id'),
                'client_secret' => config('oauth.gitlab.client_secret'),
                'code' => $request->get('code'),
                'grant_type' => 'authorization_code',
                'redirect_uri' => config('oauth.gitlab.callback_uri'),
        ]);
       $token = $response['access_token'];

       $response = Http::withHeaders(['Authorization' => 'Bearer ' . $token])
               ->get('https://gitlab.com/api/v4/user');

       $user = User::query()
               ->where('email', '=', $response['public_email'])
               ->first();

       if($user === null) {
           $user = User::create([
               'first_name' => $response['name'],
               'last_name' => '',
               'email' => $response['public_email'],
               'password' => Hash::make(Str::random(8))
           ]);
       }

       Auth::login($user);

       $request->session()->regenerate();

       return back();
    }

}

resources/views/ads/create.blade.php
@extends('layout')

@section('ads')
<!--<form class="was-validated">-->
<form class="" method="POST" action="{{route('ads.store')}}">
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title" value='{{old('title')}}' placeholder="title">
        @error('title')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea name="description" class="form-control @error('description') is-invalid @enderror" id="description" >{{old('description')}}</textarea>
        @error('description')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>


    <div class="mb-3">
        <button class="btn btn-primary" type="submit">Create ad</button>
    </div>
    @csrf
</form>
@endsection

resources/views/ads/index.blade.php
@extends('layout')

@section('ads')
@foreach($ads as $ad)
<a href="{{ route('ads.show', ['id' => $ad->id])}}"><h2> {{$ad->title}} </h2></a>
<p> {{$ad->description}} </p>
<br>
<span> {{$ad->author->first_name}} {{$ad->author->last_name}}</span>
<br>
<i>{{$ad->created_at->diffForHumans()}}</i>
@can('update', $ad)
<a href="{{ route('ads.edit', ['ad'=> $ad->id]) }}" type="button" class="btn btn-light">Edit</a>
@endcan

@can('delete', $ad)
<form action='{{ route('ads.destroy', ['ad' => $ad->id])}}' method='post'>
    @method('delete')
    @csrf
    <input type='submit' class='btn btn-light' value='Delete' />
</form>
@endcan
<hr>
@endforeach
{{ $ads->links() }}
@endsection

resources/views/ads/show.blade.php
@extends('layout')

@section('ads')
<h2> {{$ad->title}} </h2>
<p> {{$ad->description}} </p>
<br>
<span> {{$ad->author->first_name}} {{$ad->author->last_name}}</span>
<br>
<i>{{$ad->created_at->diffForHumans()}}</i>

@can('update', $ad)
<a href="{{ route('ads.edit', ['ad'=> $ad->id]) }}" type="button" class="btn btn-light">Edit</a>
@endcan

@can('delete', $ad)
<form action='{{ route('ads.destroy', ['ad' => $ad->id])}}' method='post'>
    @method('delete')
    @csrf
    <input type='submit' class='btn btn-light' value='Delete' />
</form>
@endcan
@endsection

resources/views/ads/update.blade.php
@extends('layout')

@section('ads')
<form class="" method="POST" action="{{route('ads.update', ['ad' => $ad->id])}}">
    @method('put')
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input name="title" type="text" class="form-control @error('title') is-invalid @enderror" id="title" value='{{old('title', $ad->title)}}' placeholder="title">
        @error('title')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea name="description" class="form-control @error('description') is-invalid @enderror" id="description" >{{old('description', $ad->description)}}</textarea>
        @error('description')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>


    <div class="mb-3">
        <button class="btn btn-primary" type="submit">Update ad</button>
    </div>
    @csrf
</form>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>MyAds</title>
    </head>
    <body>
        <div class="container">
            <a href = '/'><h1>My Ads site</h1></a>
            <hr/>
            <div class="row"> 
                <div class="col-8">@yield('ads')</div>
                <div class="col-4">@include('sidebar')</div>
            </div>
        </div>

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
    </body>
</html>

resources/views/sidebar.blade.php
<div class="sidebar">
    @guest
    <form class="" method="POST" action="{{ route('login') }}">
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input name="email" type="text" class="form-control @error('email') is-invalid @enderror" id="email" value='' placeholder="Email">
            @error('email')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input name="password" type="password" class="form-control @error('password') is-invalid @enderror" id="password" value='' placeholder="Password">
            @error('password')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Login</button>
        </div>
        @csrf
    </form>   
    <br>
    <a href="{{ \App\Services\GitlabService::link() }}" class="btn btn-primary">Login via Gitlab</a>
    @endguest
    
    @auth
    <div>
        <form class="" method="GET" action="{{ route('logout') }}">
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Logout</button>
            </div>
            @csrf
        </form>
    </div>   
    <div>
        <a href="{{route('ads.create')}}" class="btn btn-primary">Create ad</a>
    </div>
    @endauth
</div>